name: tensorflow_web
description: A tensorflow package for flutter web
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TensorflowPlugin
        fileName: tensorflow_web.dart
dependencies:
  tensorflow_platform_interface:
    path: ../tensorflow_platform_interface
  tensorflow_models:
    git:
      url: https://github.com/felangel/tfjs_models.dart.git
      ref: feat/estimate-single-pose
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cross_file: ^0.3.1
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.0