name: example
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  tensorflow_web:
    path: ../
  flutter:
    sdk: flutter
  cross_file: ^0.3.1
  js: ^0.6.3

dev_dependencies:
  very_good_analysis: ^2.0.0
