name: camera
description: Web platform implementation of camera
version: 0.1.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.0
