name: image_compositor

on:
  pull_request:
    paths:
      - "packages/image_compositor/**"
      - ".github/workflows/image_compositor.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/image_compositor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 2.2.0-10.1.pre
          channel: beta

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests chrome
        run: flutter test --platform chrome --no-pub --test-randomize-ordering-seed random

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
