name: tensorflow_web

on:
  pull_request:
    paths:
      - "packages/tensorflow/tensorflow_web/**"
      - ".github/workflows/tensorflow_web.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/tensorflow/tensorflow_web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 2.0.0

      - name: Install Dependencies
        run: flutter packages get
                
      - name: Install Dependencies for example
        working-directory: packages/tensorflow/tensorflow_web/example
        run: flutter packages get
      
      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --platform chrome --no-pub --test-randomize-ordering-seed random
