name: tensorflow_models_platform_interface

on:
  pull_request:
    paths:
      - "packages/tensorflow_models/tensorflow_models_platform_interface/**"
      - ".github/workflows/tensorflow_models_platform_interface.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/tensorflow_models/tensorflow_models_platform_interface
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 2.2.0-10.2.pre
          channel: master

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib

      - name: Analyze
        run: flutter analyze lib
